### ISSUE TITLE
Deployment Failed: Release Phase Command

### ISSUE THREAD

**Issue by sanicki** [flackdl/ifit-garmin-sync#10]
Thanks for making this available. I receive the following error from Heroku when trying to deploy:

> A deployment for XXXXX failed due to a release phase command in release v7.

[Heroku's documentation](https://devcenter.heroku.com/articles/release-phase#release-command-failure) says:

> A failed `release` command usually requires a fix to an app’s code.

Can you help? Garmin and iFit usernames and passwords have been double-checked to be correct.

**Comment by flackdl** [comment]
Hey, give it another try.  I just committed a change which worked for me
just now.  I had to pin the python version in Heroku.

**Comment by sanicki** [comment]
Works. Thank you!
