### ISSUE TITLE
November sunset of free Heroku Dynos

### ISSUE THREAD

**Issue by sanicki** [flackdl/ifit-garmin-sync#11]
Heroku is sunsetting free dynos in November. Are there any free alternatives to keep running the sync?

![image](https://user-images.githubusercontent.com/6764844/190911112-c563cf4e-cc05-4f08-b066-e23102352ff4.png)

https://devcenter.heroku.com/articles/free-dyno-hours

**Comment by flackdl** [comment]
Good question. I was disappointed to hear they were no longer offering
their free tiers.  There are plenty of heroku alternatives, but you won't
have the "one click" install I built for Heroku, unfortunately.  You'll
have to wire some things up yourselves.  However, if you find a great
alternative service, maybe we can still set up the one-click thing.  I
don't have time to investigate but will happily help with whatever you find.

**Comment by sanicki** [comment]
[Docker image](https://davelms.medium.com/build-your-docker-images-automatically-when-pushing-new-code-to-github-394f4c1679cc)?

**Comment by flackdl** [comment]
Yeah, it's set up to build itself as a Docker image, but you'll have to
find a hosting provider that offers free database services (postgres &
redis) like Heroku.   Do you have one in mind?

Postgres stores all the database records like workouts, and redis is the
in-memory database that manages the task queue (syncing workouts).

**Comment by sanicki** [comment]
I was able to fire up an old Synology NAS, install Docker and Portainer, and then install 
ifit-garmin-sync from [docker-compose.yml](https://github.com/flackdl/ifit-garmin-sync/blob/main/docker-compose.yml) using my IFIT_USER, IFIT_PASS, GARMIN_USER, and GARMIN_PASS info as environment variables. (I'm not sure if that was the right place to put those.)

It did not like postgres trying to use local port 5432, so I had to map local port 5433 to container port 5432 to get it to run.

I waited awhile but did not see any log activity from either redis or postgres, and iFit workouts weren't appearing in Garmin.

So I set up periodic curls of "/workouts/export" on ports 5432, 5433, and 6379 (since I wasn't sure which would be correct.) Still nothing.

A little knowledge is a dangerous thing. I'm not really sure what I'm doing and your help would be appreciated.

**Comment by flackdl** [comment]
Ah, ok, if you have that level of experience I'll tweak the
docker-compose.yml file so it'll just work.  I'll post back here when it's
done and you should just be able to bring everything up on your NAS.

**Comment by flackdl** [comment]
Sorry, I got bogged down with work.  I hope to get to this eventually.

**Comment by flackdl** [comment]
Ok I updated this be runnable via docker/docker-compose.  See instructions and let me know if you have any issues.

**Comment by sanicki** [comment]
I see in the README you say:

> Copy the `env.template` file to `env`:
> `cp env.template env`
> Populate the environment variables in env then start up everything with:
> `docker-compose up -d --build`

I'm not sure how to do this in Portainer, where I'm just used to adding environment variables like this:

![image](https://user-images.githubusercontent.com/6764844/197849972-07ab56e8-2d64-41d4-b5b3-638d1257eb57.png)

**Comment by flackdl** [comment]
Oh, ok, I think I understand.  I just updated this repo to support environment variables defined in Portainer/elsewhere.  Please update and try again by entering in the environment variables in the Portainer GUI.

**Comment by sanicki** [comment]
I had to map local port 5433 to container port 5432 to get it to run successfully:

![image](https://user-images.githubusercontent.com/6764844/197864199-2efeb6bb-3d46-4959-8081-e7507a43d4ee.png)

Once I have an iFit workout complete I'll be able to check if it's working, though nothing's showing up at port `8080` of the Synology NAS:

> You should now be able to access the dashboard at http://localhost:8080/.

There's also not much activity in the logs.

Log for ifit-garmin-sync_postgres:
```
,
PostgreSQL Database directory appears to contain a database; Skipping initialization,
,
2022-10-25 19:13:53.262 UTC [1] LOG:  starting PostgreSQL 12.12 on x86_64-pc-linux-musl, compiled by gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219, 64-bit,
2022-10-25 19:13:53.262 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432,
2022-10-25 19:13:53.262 UTC [1] LOG:  listening on IPv6 address "::", port 5432,
2022-10-25 19:13:53.266 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432",
2022-10-25 19:13:53.317 UTC [20] LOG:  database system was shut down at 2022-10-25 19:10:44 UTC,
2022-10-25 19:13:53.375 UTC [1] LOG:  database system is ready to accept connections,
```
Log for ifit-garmin-sync_redis:
```
1:C 25 Oct 2022 19:04:23.027 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo,
1:C 25 Oct 2022 19:04:23.027 # Redis version=5.0.14, bits=64, commit=00000000, modified=0, pid=1, just started,
1:C 25 Oct 2022 19:04:23.028 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf,
1:M 25 Oct 2022 19:04:23.033 * Running mode=standalone, port=6379.,
1:M 25 Oct 2022 19:04:23.033 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.,
1:M 25 Oct 2022 19:04:23.033 # Server initialized,
1:M 25 Oct 2022 19:04:23.033 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.,
1:M 25 Oct 2022 19:04:23.034 * Ready to accept connections,
```

**Comment by flackdl** [comment]
> though nothing's showing up at port 8080 of the Synology NAS:

You don't see the dashboard when you visit http://localhost:8080/? Or just no workouts appear?

For relevant logs, you need to look at the `celery` container. That's the task queue/processor application.

**Comment by sanicki** [comment]
When I try accessing port 8080 of the Synology NAS, I only get back:

![image](https://user-images.githubusercontent.com/6764844/197867061-ca5ad6c1-407b-4a7a-9d8e-09d8c99974d4.png)

> For relevant logs, you need to look at the `celery` container. That's the task queue/processor application.

Hmm. Those two containers (originally named "ifitgarminsync_postgres" and "redis") are all that get deployed by the [stack](https://www.portainer.io/blog/stacks-docker-compose-the-portainer-way).

I do see the following under Images:

![image](https://user-images.githubusercontent.com/6764844/197869985-a04ba1f9-7b9b-44db-ab5e-617bcf5ffe2a.png)

**Comment by flackdl** [comment]
You definitely need all 4 containers in this stack: 

- postgres (database)
- redis (in-memory database for task queue)
- ifit (my app)
- celery (my app's task queue).


I installed Portainer and created a new "stack" via this github repo (it strangely gave me several transient errors but it eventually worked).  I then added the environment varibles via Portainer's GUI for this stack.  I *think* it restarts the relevant containers when you update env vars, but maybe I had to click **redeploy** but i'm not certain.  Anyway, it eventually worked.

![image](https://user-images.githubusercontent.com/6498354/197871761-95d3d89f-02dd-409b-8de7-21313fa20bec.png)


![image](https://user-images.githubusercontent.com/6498354/197871973-70129b1a-7b1b-412a-8fc2-ff3c7a254c60.png)

**Comment by flackdl** [comment]
Here's my stack that automatically populated via this GitHub's repo connection:

![image](https://user-images.githubusercontent.com/6498354/197872828-8dabc0f0-e2cf-48a3-8b9e-27889873dcba.png)

**Comment by flackdl** [comment]
I would destroy your stack and create a new one to make sure you're starting fresh.

**Comment by sanicki** [comment]
Deleted the containers, stack, and images. Now I'm getting:
![image](https://user-images.githubusercontent.com/6764844/197876978-eabab9f4-98ce-4fb2-9a66-7a15c47464f7.png)

**Comment by flackdl** [comment]
I'm not sure what's going on.  I installed Portainer (community edition), created a new stack using this GitHub URL, set environment variables, and it populated & ran all the containers successfully.  

I am not experienced with Portainer so I don't have much advice other than the steps I did.  Maybe you should just run `docker-compose` like my instructions and see if that works for you.  You don't **need** portainer to make this work, it's just a nice interface.

**Comment by sanicki** [comment]
I was getting in my own way. I'd saved the stack as a custom app template which apparently mucked up the paths somehow I couldn't resolve.

Creating a new stack still failed on the port conflict, but once I changed the local port in the container I was able to redeploy the stack and it completed successfully.

Thanks for everything!
