### ISSUE TITLE
API path changed?

### ISSUE THREAD

**Issue by hieronymousch** [flackdl/ifit-garmin-sync#2]
Hi, 

first a big thank you for your efforts to get this working. One can only hope that one day there will better integration between all the closed gardens in the fitness world.

anyway, I tried to install the script on one of my Debian servers. Installation works fine but the script runs into a 404 error for the API path, currently set on IFIT_URL_AUTH = 'https://www.ifit.com/web-api/login'
Has this changed?

Thanks,

**Comment by ploveland** [comment]
It's working as-is for me.

**Comment by flackdl** [comment]
@hieronymousch, sorry for the late response.  I missed this somehow.  I just tested this and it authenticates and syncs my workouts successfully.  If you can show me some logs maybe I can help more.

**Comment by hieronymousch** [comment]
I gave up (to much customisation required due to other used ports) and went for the Heroku, which worked flawless. Thanks for your work!
