### ISSUE TITLE
Distance incorrect

### ISSUE THREAD

**Issue by ploveland** [flackdl/ifit-garmin-sync#7]
The distances that are showing in Garmin are different than what is the in iFit record. I checked both of the exports, TCX and CSV, and the distance is correct in both, but in Connect, it is showing the distance of the workout (expected distance) rather than the distance that I actually did. I've been looking through the code both here and in garmin-uploader, and see where it appears to be uploading in workflow.py, but being new to the code, can't see where the distance is done. Perhaps it's just looping through the columns and adding the info via the API without being explicitly set.  So on that note, I'm thinking that if it were in garmin-uploader, there'd be a bug about it already from others who used it outside of us using the iFit version. But I haven't been able to find that out for sure, or if there's some sort of issue with the downloaded file vs. doing it through the UI on iFit.

**Comment by flackdl** [comment]
Yeah there are reports of inaccurate/missing values when exporting from iFit in the tcx/csv formats.  

Here's the two threads I started with some relevant comments regarding incorrect data:

- https://www.reddit.com/r/iFit/comments/lafmpn/sync_ifit_to_garminstrava/
- https://www.reddit.com/r/nordictrack/comments/laxttp/sync_ifit_to_garminstrava/

And someone wrote up a lot of iFit export issues here: https://rpubs.com/markbulk/677317

This repository doesn't do *any* massaging of actual data, and I don't think *garmin-uploader* does either.  Let  me know if you have any ideas.

**Comment by ploveland** [comment]
Ah yea, that's too bad. But hey, it's free right? I'll take a look with crossed-fingers I see something. Thanks!
